# Generated by Django 5.0.1 on 2026-03-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFiscalSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=200, verbose_name='Nombre comercial')),
                ('nombre_legal', models.CharField(blank=True, max_length=300, verbose_name='Razón social / Nombre legal')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('logo_url', models.CharField(blank=True, max_length=500, verbose_name='URL del logotipo')),
                ('leyenda_ticket', models.TextField(default='Gracias por su compra. Este documento no es una factura fiscal.', verbose_name='Leyenda del ticket')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sede', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='config_fiscal', to='branches.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Configuración fiscal de sede',
                'db_table': 'billing_config_fiscal_sede',
            },
        ),
    ]
