# Generated by Django 5.0.1 on 2026-03-11 15:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('fecha_nac', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token QR')),
                ('foto_url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL de foto')),
                ('puntos', models.PositiveIntegerField(default=0, verbose_name='Puntos acumulados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de cliente',
                'verbose_name_plural': 'Perfiles de clientes',
                'db_table': 'customers_perfiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
