# Generated by Django 5.0.1 on 2026-02-26 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'inventory_categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('FINALIZADA', 'Finalizada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='branches.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Auditoría de Inventario',
                'verbose_name_plural': 'Auditorías de Inventario',
                'db_table': 'inventory_auditorias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de compra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventory.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'inventory_productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EntradaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad recibida')),
                ('cost_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo unitario')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_inventario', to='branches.sede', verbose_name='Sede')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='inventory.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Entrada de Inventario',
                'verbose_name_plural': 'Entradas de Inventario',
                'db_table': 'inventory_entradas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema', models.IntegerField(verbose_name='Stock en sistema')),
                ('stock_fisico', models.IntegerField(blank=True, null=True, verbose_name='Conteo físico')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.auditoriainventario', verbose_name='Auditoría')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de Auditoría',
                'verbose_name_plural': 'Ítems de Auditoría',
                'db_table': 'inventory_auditoria_items',
                'unique_together': {('auditoria', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('min_quantity', models.IntegerField(default=5, verbose_name='Stock mínimo (alerta)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.producto', verbose_name='Producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='branches.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'db_table': 'inventory_stock',
                'unique_together': {('producto', 'sede')},
            },
        ),
    ]
