# Generated by Django 5.0.1 on 2026-02-27 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaFabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('OEM', 'OEM (Original Equipment Manufacturer)'), ('AFTERMARKET', 'Aftermarket'), ('GENERICO', 'Genérico')], default='AFTERMARKET', max_length=20, verbose_name='Tipo')),
                ('pais', models.CharField(blank=True, default='', max_length=50, verbose_name='País de origen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Marca Fabricante',
                'verbose_name_plural': 'Marcas Fabricante',
                'db_table': 'inventory_marcas_fabricante',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarcaMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Marca')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Marca de Moto',
                'verbose_name_plural': 'Marcas de Moto',
                'db_table': 'inventory_marcas_moto',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, default='', help_text='EAN-13, Code128 u otro. Se genera automáticamente si se deja vacío.', max_length=50, verbose_name='Código de barras'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_descontinuado',
            field=models.BooleanField(default=False, verbose_name='Descontinuado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_universal',
            field=models.BooleanField(default=False, help_text='Aplica a múltiples modelos sin restricción de fitment.', verbose_name='Es universal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='numero_parte_aftermarket',
            field=models.CharField(blank=True, default='', help_text='Número de parte del fabricante de la refacción.', max_length=80, verbose_name='N° parte aftermarket'),
        ),
        migrations.AddField(
            model_name='producto',
            name='numero_parte_oem',
            field=models.CharField(blank=True, default='', help_text='Número de parte del fabricante original de la moto.', max_length=80, verbose_name='N° de parte OEM'),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_mayoreo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio mayoreo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_parte',
            field=models.CharField(choices=[('OEM', 'OEM (Original)'), ('AFTERMARKET', 'Aftermarket'), ('REMANUFACTURADO', 'Remanufacturado')], default='AFTERMARKET', max_length=20, verbose_name='Tipo de parte'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion_almacen',
            field=models.CharField(blank=True, default='', help_text='Formato: PASILLO-RACK-NIVEL-POS  Ej: A-03-2-B', max_length=30, verbose_name='Ubicación almacén'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('PIEZA', 'Pieza'), ('PAR', 'Par'), ('KIT', 'Kit'), ('LITRO', 'Litro'), ('METRO', 'Metro'), ('ROLLO', 'Rollo')], default='PIEZA', max_length=10, verbose_name='Unidad de medida'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca_fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventory.marcafabricante', verbose_name='Marca fabricante'),
        ),
        migrations.CreateModel(
            name='ModeloMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('año_desde', models.SmallIntegerField(default=2018, verbose_name='Año desde')),
                ('año_hasta', models.SmallIntegerField(blank=True, null=True, verbose_name='Año hasta')),
                ('cilindraje', models.SmallIntegerField(blank=True, null=True, verbose_name='Cilindraje (cc)')),
                ('tipo_motor', models.CharField(choices=[('2T', '2 Tiempos'), ('4T', '4 Tiempos'), ('ELECTRICO', 'Eléctrico')], default='4T', max_length=10, verbose_name='Tipo de motor')),
                ('tipo_moto', models.CharField(choices=[('CARGO', 'Carga / Trabajo'), ('NAKED', 'Naked / Urbana'), ('DEPORTIVA', 'Deportiva'), ('SCOOTER', 'Scooter / Automática'), ('OFF_ROAD', 'Off Road / Enduro'), ('CRUCERO', 'Crucero')], default='CARGO', max_length=20, verbose_name='Tipo de moto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='inventory.marcamoto', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo de Moto',
                'verbose_name_plural': 'Modelos de Moto',
                'db_table': 'inventory_modelos_moto',
                'ordering': ['marca__name', 'modelo', 'año_desde'],
                'unique_together': {('marca', 'modelo', 'año_desde')},
            },
        ),
        migrations.CreateModel(
            name='CompatibilidadPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_desde', models.SmallIntegerField(blank=True, null=True, verbose_name='Año desde (override)')),
                ('año_hasta', models.SmallIntegerField(blank=True, null=True, verbose_name='Año hasta (override)')),
                ('nota', models.CharField(blank=True, default='', max_length=200, verbose_name='Nota')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades', to='inventory.producto')),
                ('modelo_moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades', to='inventory.modelomoto')),
            ],
            options={
                'verbose_name': 'Compatibilidad',
                'verbose_name_plural': 'Compatibilidades',
                'db_table': 'inventory_compatibilidad_pieza',
                'unique_together': {('producto', 'modelo_moto')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='aplicaciones',
            field=models.ManyToManyField(blank=True, related_name='piezas', through='inventory.CompatibilidadPieza', to='inventory.modelomoto', verbose_name='Modelos compatibles'),
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='inventory.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'db_table': 'inventory_subcategorias',
                'ordering': ['categoria__name', 'name'],
                'unique_together': {('categoria', 'name')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventory.subcategoria', verbose_name='Subcategoría'),
        ),
    ]
