# Generated by Django 5.0.1 on 2026-03-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_marcafabricante_marcamoto_producto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen del producto'),
        ),
    ]
