# Generated by Django 5.0.1 on 2026-03-09 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoApertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('expires_at', models.DateTimeField(verbose_name='Expira el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Generado el')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codigos_generados', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codigos_apertura', to='branches.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Código de apertura',
                'verbose_name_plural': 'Códigos de apertura',
                'db_table': 'sales_codigos_apertura',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('status', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10, verbose_name='Estado')),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_caja', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_caja', to='branches.sede', verbose_name='Sede')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.codigoapertura', verbose_name='Código usado')),
            ],
            options={
                'verbose_name': 'Apertura de caja',
                'verbose_name_plural': 'Aperturas de caja',
                'db_table': 'sales_aperturas_caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddConstraint(
            model_name='aperturacaja',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ABIERTA')), fields=('cajero',), name='unique_cajero_caja_abierta'),
        ),
    ]
