# Generated by Django 5.0.1 on 2026-03-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0002_codigoapertura_aperturacaja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='customers.clienteprofile', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='puntos_ganados',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntos ganados'),
        ),
    ]
