# Generated by Django 5.0.1 on 2026-03-13 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_venta_cliente_venta_puntos_ganados'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='reportes_caja/%Y/%m/', verbose_name='Archivo PDF')),
                ('total_ventas', models.PositiveIntegerField(default=0)),
                ('total_canceladas', models.PositiveIntegerField(default=0)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apertura', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reporte', to='sales.aperturacaja', verbose_name='Apertura de caja')),
            ],
            options={
                'verbose_name': 'Reporte de caja',
                'verbose_name_plural': 'Reportes de caja',
                'db_table': 'sales_reportes_caja',
                'ordering': ['-created_at'],
            },
        ),
    ]
