# Generated by Django 5.0.1 on 2026-03-12 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0003_producto_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.CharField(blank=True, default='', max_length=300, verbose_name='Notas')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_bodega', to='branches.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Pedido de Bodega',
                'verbose_name_plural': 'Pedidos de Bodega',
                'db_table': 'pedidos_bodega',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PedidoBodegaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('ubicacion', models.CharField(blank=True, default='', max_length=100, verbose_name='Ubicación en almacén')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedidobodega', verbose_name='Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_items', to='inventory.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de Pedido',
                'verbose_name_plural': 'Ítems de Pedido',
                'db_table': 'pedidos_bodega_items',
            },
        ),
    ]
