# Generated by Django 5.0.1 on 2026-02-26 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('users', '0002_customuser_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrador'), ('ENCARGADO', 'Encargado de Sede'), ('WORKER', 'Trabajador'), ('CASHIER', 'Cajero'), ('CUSTOMER', 'Cliente')], default='CUSTOMER', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de entrada')),
                ('hora_fin', models.TimeField(verbose_name='Hora de salida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='branches.sede', verbose_name='Sede')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'users_turnos',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('user', 'dia_semana')},
            },
        ),
    ]
