# Generated by Django 5.0.1 on 2026-02-27 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_attempts',
            field=models.IntegerField(default=0, verbose_name='Intentos fallidos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unlock_requested',
            field=models.BooleanField(default=False, verbose_name='Solicitud de desbloqueo'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de restablecimiento',
                'verbose_name_plural': 'Tokens de restablecimiento',
                'db_table': 'users_password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
