# Generated by Django 5.0.1 on 2026-02-27 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_locked_until_customuser_login_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Inicio de sesión exitoso'), ('LOGIN_FAILED', 'Intento fallido'), ('ACCOUNT_LOCKED', 'Cuenta bloqueada'), ('ACCOUNT_UNLOCKED', 'Cuenta desbloqueada'), ('UNLOCK_REQUESTED', 'Solicitud de desbloqueo'), ('PASSWORD_RESET_REQ', 'Solicitud de restablecimiento'), ('PASSWORD_RESET_DONE', 'Contraseña restablecida')], max_length=30, verbose_name='Tipo de evento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('details', models.TextField(blank=True, default='', verbose_name='Detalles')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de acceso',
                'verbose_name_plural': 'Registros de acceso',
                'db_table': 'users_login_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
